import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TopbarManu } from "@/components/ui/topbar-manu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-br" 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col w-300 m-auto bg-linear-to-b from-indigo-950 to-indigo-500 text-white">
        <TopbarManu/>
        {children}
        </body>
    </html>
  );
}
